BoosterSeat: bst::SoftwareTimer Class Reference
bst::SoftwareTimer Class Reference
A software timer class for manual control.
#include <timer.hpp>
Public Member Functions
SoftwareTimer ()=default
Default constructor.
bool isDone () const override
Check if the timer is done.
void reset () override
Reset the timer - Sets the timer to not done.
void setDone () override
Set the timer to done.
void setNotDone ()
Set the timer to not done.
void setTimeout (int timeout_ms) override
Stubbed out - Does nothing.
Private Attributes
bool is_done_ = false
The done state of the timer.
Detailed Description
A software timer class for manual control.
Constructor & Destructor Documentation
SoftwareTimer()
bst::SoftwareTimer::SoftwareTimer () default
Default constructor.
Member Function Documentation
reset()
void bst::SoftwareTimer::reset () inline override virtual
Reset the timer - Sets the timer to not done.
Implements bst::ITimer.
References is_done_.
Referenced by TEST().
isDone()
bool bst::SoftwareTimer::isDone () const inline override virtual
Check if the timer is done.
Implements bst::ITimer.
References is_done_.
Referenced by TEST().
setTimeout()
void bst::SoftwareTimer::setTimeout (int timeout_ms) inline override virtual
Stubbed out - Does nothing.
Implements bst::ITimer.
setDone()
void bst::SoftwareTimer::setDone () inline override virtual
Set the timer to done.
Implements bst::ITimer.
References is_done_.
Referenced by TEST().
setNotDone()
void bst::SoftwareTimer::setNotDone () inline
Set the timer to not done.
References is_done_.
Referenced by TEST().
Member Data Documentation
is_done_
bool bst::SoftwareTimer::is_done_ = false private
The done state of the timer.
Referenced by isDone(), reset(), setDone(), and setNotDone().