BoosterSeat: bst::Stopwatch< StopwatchClock > Class Template Reference
bst::Stopwatch< StopwatchClock > Class Template Reference
A simple stopwatch class. Basic start (resume), stop (pause), and reset functionality.
#include <stopwatch.hpp>
Public Types
enum class Scale { SECONDS , MILLISECONDS , MICROSECONDS }
The resolution/scale of the time returned by elapsed()
Public Member Functions
Stopwatch ()=default
Construct a new Stopwatch object. The stopwatch is stopped.
~Stopwatch ()=default
Default destructor.
int64_t elapsedMicroseconds () const
Get the elapsed time in microseconds.
double elapsedMicrosecondsF () const
Get the elapsed time in microseconds in a floating point format.
int64_t elapsedMilliseconds () const
Get the elapsed time in milliseconds.
double elapsedMillisecondsF () const
Get the elapsed time in milliseconds in a floating point format.
int64_t elapsedSeconds () const
Get the elapsed time in seconds.
double elapsedSecondsF () const
Get the elapsed time in seconds in a floating point format.
bool isRunning () const
Returns the current state of the stopwatch.
void pause ()
alias for stop() as it does what you want it to do.
void reset (bool stop=true)
Resets the elapsed time. The stopwatch will keep running by default.
void resume ()
alias for start() as it does what you want it to do.
void start ()
Start the stopwatch.
void stop ()
Stops/Pauses the stopwatch. Does not reset the elapsed time.
Protected Types
enum class State { RUNNING , STOPPED }
The state of the stopwatch.
Protected Member Functions
bst::clck::Duration getElapsed () const
Handles the timekeeping.
Private Attributes
clck::Clock clock_
clck::Duration elapsed_ = clck::Duration::zero()
clck::TimePoint start_ = clck::TimePoint::min()
State state_ = State::STOPPED
clck::TimePoint stop_time_ = clck::TimePoint::min()
Detailed Description
template<class StopwatchClock = clck::Clock>
class bst::Stopwatch< StopwatchClock >
A simple stopwatch class. Basic start (resume), stop (pause), and reset functionality.
Template Parameters
StopwatchClock - The clock to use for timing. Defaults to the high_resolution_clock.
Member Enumeration Documentation
Scale
template<class StopwatchClock = clck::Clock> enum bst::Stopwatch::Scale strong
The resolution/scale of the time returned by elapsed()
Enumerator
SECONDS
MILLISECONDS
MICROSECONDS
State
enum bst::IStopwatch::State strong protected inherited
The state of the stopwatch.
Enumerator
RUNNING
STOPPED
Constructor & Destructor Documentation
Stopwatch()
template<class StopwatchClock = clck::Clock> bst::Stopwatch< StopwatchClock >::Stopwatch () default
Construct a new Stopwatch object. The stopwatch is stopped.
~Stopwatch()
template<class StopwatchClock = clck::Clock> bst::Stopwatch< StopwatchClock >::~Stopwatch () default
Default destructor.
Member Function Documentation
start()
template<class StopwatchClock = clck::Clock> void bst::Stopwatch< StopwatchClock >::start () inline virtual
Start the stopwatch.
Exceptions
BoosterSeatException if the stopwatch is already running.
Implements bst::IStopwatch.
References bst::Stopwatch< StopwatchClock >::clock_, bst::IStopwatch::RUNNING, bst::Stopwatch< StopwatchClock >::start_, bst::Stopwatch< StopwatchClock >::state_, and bst::IStopwatch::STOPPED.
Referenced by bst::Stopwatch< StopwatchClock >::resume(), and TEST().
stop()
template<class StopwatchClock = clck::Clock> void bst::Stopwatch< StopwatchClock >::stop () inline virtual
Stops/Pauses the stopwatch. Does not reset the elapsed time.
Implements bst::IStopwatch.
References bst::Stopwatch< StopwatchClock >::clock_, bst::Stopwatch< StopwatchClock >::elapsed_, bst::IStopwatch::RUNNING, bst::Stopwatch< StopwatchClock >::start_, bst::Stopwatch< StopwatchClock >::state_, bst::Stopwatch< StopwatchClock >::stop_time_, and bst::IStopwatch::STOPPED.
Referenced by bst::Stopwatch< StopwatchClock >::pause(), bst::Stopwatch< StopwatchClock >::reset(), and TEST().
reset()
template<class StopwatchClock = clck::Clock> void bst::Stopwatch< StopwatchClock >::reset (bool stop = true) inline virtual
Resets the elapsed time. The stopwatch will keep running by default.
Parameters
stop If true, the stopwatch will be stopped.
Implements bst::IStopwatch.
References bst::Stopwatch< StopwatchClock >::elapsed_, bst::Stopwatch< StopwatchClock >::state_, bst::Stopwatch< StopwatchClock >::stop(), and bst::IStopwatch::STOPPED.
Referenced by TEST().
isRunning()
template<class StopwatchClock = clck::Clock> bool bst::Stopwatch< StopwatchClock >::isRunning () const inline virtual
Returns the current state of the stopwatch.
Implements bst::IStopwatch.
References bst::IStopwatch::RUNNING, and bst::Stopwatch< StopwatchClock >::state_.
Referenced by TEST().
elapsedMicroseconds()
template<class StopwatchClock = clck::Clock> int64_t bst::Stopwatch< StopwatchClock >::elapsedMicroseconds () const inline virtual
Get the elapsed time in microseconds.
Implements bst::IStopwatch.
References bst::Stopwatch< StopwatchClock >::getElapsed().
Referenced by TEST().
elapsedMicrosecondsF()
template<class StopwatchClock = clck::Clock> double bst::Stopwatch< StopwatchClock >::elapsedMicrosecondsF () const inline virtual
Get the elapsed time in microseconds in a floating point format.
Implements bst::IStopwatch.
References bst::Stopwatch< StopwatchClock >::getElapsed().
Referenced by TEST().
elapsedMilliseconds()
template<class StopwatchClock = clck::Clock> int64_t bst::Stopwatch< StopwatchClock >::elapsedMilliseconds () const inline virtual
Get the elapsed time in milliseconds.
Implements bst::IStopwatch.
References bst::Stopwatch< StopwatchClock >::getElapsed().
elapsedMillisecondsF()
template<class StopwatchClock = clck::Clock> double bst::Stopwatch< StopwatchClock >::elapsedMillisecondsF () const inline virtual
Get the elapsed time in milliseconds in a floating point format.
Implements bst::IStopwatch.
References bst::Stopwatch< StopwatchClock >::getElapsed().
Referenced by TEST().
elapsedSeconds()
template<class StopwatchClock = clck::Clock> int64_t bst::Stopwatch< StopwatchClock >::elapsedSeconds () const inline virtual
Get the elapsed time in seconds.
Implements bst::IStopwatch.
References bst::Stopwatch< StopwatchClock >::getElapsed().
elapsedSecondsF()
template<class StopwatchClock = clck::Clock> double bst::Stopwatch< StopwatchClock >::elapsedSecondsF () const inline virtual
Get the elapsed time in seconds in a floating point format.
Implements bst::IStopwatch.
References bst::Stopwatch< StopwatchClock >::getElapsed().
Referenced by TEST().
pause()
template<class StopwatchClock = clck::Clock> void bst::Stopwatch< StopwatchClock >::pause () inline virtual
alias for stop() as it does what you want it to do.
Implements bst::IStopwatch.
References bst::Stopwatch< StopwatchClock >::stop().
resume()
template<class StopwatchClock = clck::Clock> void bst::Stopwatch< StopwatchClock >::resume () inline virtual
alias for start() as it does what you want it to do.
Implements bst::IStopwatch.
References bst::Stopwatch< StopwatchClock >::start().
getElapsed()
template<class StopwatchClock = clck::Clock> bst::clck::Duration bst::Stopwatch< StopwatchClock >::getElapsed () const inline protected
Handles the timekeeping.
Returns
clck::Duration - The elapsed time
References bst::Stopwatch< StopwatchClock >::clock_, bst::Stopwatch< StopwatchClock >::elapsed_, bst::IStopwatch::RUNNING, bst::Stopwatch< StopwatchClock >::start_, and bst::Stopwatch< StopwatchClock >::state_.
Referenced by bst::Stopwatch< StopwatchClock >::elapsedMicroseconds(), bst::Stopwatch< StopwatchClock >::elapsedMicrosecondsF(), bst::Stopwatch< StopwatchClock >::elapsedMilliseconds(), bst::Stopwatch< StopwatchClock >::elapsedMillisecondsF(), bst::Stopwatch< StopwatchClock >::elapsedSeconds(), and bst::Stopwatch< StopwatchClock >::elapsedSecondsF().
Member Data Documentation
clock_
template<class StopwatchClock = clck::Clock> clck::Clock bst::Stopwatch< StopwatchClock >::clock_ private
Referenced by bst::Stopwatch< StopwatchClock >::getElapsed(), bst::Stopwatch< StopwatchClock >::start(), and bst::Stopwatch< StopwatchClock >::stop().
start_
template<class StopwatchClock = clck::Clock> clck::TimePoint bst::Stopwatch< StopwatchClock >::start_ = clck::TimePoint::min() private
Referenced by bst::Stopwatch< StopwatchClock >::getElapsed(), bst::Stopwatch< StopwatchClock >::start(), and bst::Stopwatch< StopwatchClock >::stop().
stop_time_
template<class StopwatchClock = clck::Clock> clck::TimePoint bst::Stopwatch< StopwatchClock >::stop_time_ = clck::TimePoint::min() private
Referenced by bst::Stopwatch< StopwatchClock >::stop().
elapsed_
template<class StopwatchClock = clck::Clock> clck::Duration bst::Stopwatch< StopwatchClock >::elapsed_ = clck::Duration::zero() private
Referenced by bst::Stopwatch< StopwatchClock >::getElapsed(), bst::Stopwatch< StopwatchClock >::reset(), and bst::Stopwatch< StopwatchClock >::stop().
state_
template<class StopwatchClock = clck::Clock> State bst::Stopwatch< StopwatchClock >::state_ = State::STOPPED private
Referenced by bst::Stopwatch< StopwatchClock >::getElapsed(), bst::Stopwatch< StopwatchClock >::isRunning(), bst::Stopwatch< StopwatchClock >::reset(), bst::Stopwatch< StopwatchClock >::start(), and bst::Stopwatch< StopwatchClock >::stop().