BoosterSeat: BoosterSeat::Timer Class Reference
BoosterSeat::Timer Class Reference
#include <timer.hpp>
Public Member Functions
Timer ()
Timer (int timeout_ms)
~Timer ()=default
bool isDone () const
void reset ()
void setTimeout (int timeout_ms)
Private Attributes
clck::TimePoint start_ = clck::Clock::now()
int timeout_ms_
Constructor & Destructor Documentation
Timer() [1/2]
Timer::Timer (int timeout_ms)
Timer() [2/2]
Timer::Timer ()
~Timer()
BoosterSeat::Timer::~Timer () default
Member Function Documentation
reset()
void Timer::reset ()
References BoosterSeat::clck::now(), and start_.
Referenced by main().
isDone()
bool Timer::isDone () const
References BoosterSeat::clck::now(), start_, and timeout_ms_.
Referenced by main().
setTimeout()
void Timer::setTimeout (int timeout_ms)
References timeout_ms_.
Member Data Documentation
start_
clck::TimePoint BoosterSeat::Timer::start_ = clck::Clock::now() private
Referenced by isDone(), and reset().
timeout_ms_
int BoosterSeat::Timer::timeout_ms_ private
Referenced by isDone(), and setTimeout().