BoosterSeat: BoosterSeat::Stopwatch Class Reference
BoosterSeat::Stopwatch Class Reference
#include <stopwatch.hpp>
Public Types
enum class State { RUNNING , STOPPED }
Public Member Functions
Stopwatch ()
~Stopwatch ()=default
double elapsed (Resolution resolution=Resolution::SECONDS) const
void reset ()
void start ()
State state () const
void stop ()
Private Attributes
clck::Clock clock_ = clck::Clock()
clck::Duration elapsed_ = clck::Duration::zero()
clck::TimePoint start_ = clck::TimePoint::min()
State state_ = State::STOPPED
clck::TimePoint stop_time_ = clck::TimePoint::min()
Member Enumeration Documentation
State
enum BoosterSeat::Stopwatch::State strong
Enumerator
RUNNING
STOPPED
Constructor & Destructor Documentation
Stopwatch()
Stopwatch::Stopwatch ()
References state_, and STOPPED.
~Stopwatch()
BoosterSeat::Stopwatch::~Stopwatch () default
Member Function Documentation
start()
void Stopwatch::start ()
References clock_, RUNNING, start_, state_, and STOPPED.
Referenced by TEST().
stop()
void Stopwatch::stop ()
References clock_, elapsed_, RUNNING, start_, state_, stop_time_, and STOPPED.
Referenced by TEST().
reset()
void Stopwatch::reset ()
References elapsed_, state_, and STOPPED.
state()
Stopwatch::State Stopwatch::state () const
References state_.
Referenced by TEST().
elapsed()
double Stopwatch::elapsed (Resolution resolution = Resolution::SECONDS) const
References clock_, elapsed_, BoosterSeat::MICROSECONDS, BoosterSeat::MILLISECONDS, RUNNING, BoosterSeat::SECONDS, start_, and state_.
Referenced by TEST().
Member Data Documentation
clock_
clck::Clock BoosterSeat::Stopwatch::clock_ = clck::Clock() private
Referenced by elapsed(), start(), and stop().
start_
clck::TimePoint BoosterSeat::Stopwatch::start_ = clck::TimePoint::min() private
Referenced by elapsed(), start(), and stop().
stop_time_
clck::TimePoint BoosterSeat::Stopwatch::stop_time_ = clck::TimePoint::min() private
Referenced by stop().
elapsed_
clck::Duration BoosterSeat::Stopwatch::elapsed_ = clck::Duration::zero() private
Referenced by elapsed(), reset(), and stop().
state_
State BoosterSeat::Stopwatch::state_ = State::STOPPED private
Referenced by Stopwatch(), elapsed(), reset(), start(), state(), and stop().