BoosterSeat: bst::Timer Class Reference
bst::Timer Class Reference
A simple timer class for timing events.
#include <timer.hpp>
Public Member Functions
Timer ()
Create a new timer with a timeout of 0. Must call setTimeout before using.
Timer (int timeout_ms)
Create a new timer with a timeout.
bool isDone () const override
Check if the timer has expired.
void reset () override
Reset the timer to the current time.
void setDone () override
Set the timer to be done. Changes the start time.
void setTimeout (int timeout_ms) override
Set the timeout of the timer.
Private Attributes
bst::clck::TimePoint start_ = bst::clck::Clock::now()
int timeout_ms_
Detailed Description
A simple timer class for timing events.
Constructor & Destructor Documentation
Timer() [1/2]
bst::Timer::Timer (int timeout_ms)
Create a new timer with a timeout.
Parameters
timeout_ms The timeout in milliseconds
Timer() [2/2]
bst::Timer::Timer ()
Create a new timer with a timeout of 0. Must call setTimeout before using.
Member Function Documentation
reset()
void bst::Timer::reset () override virtual
Reset the timer to the current time.
Implements bst::ITimer.
References bst::clck::now(), and start_.
Referenced by main(), and TEST().
isDone()
bool bst::Timer::isDone () const override virtual
Check if the timer has expired.
Returns
true if the timer has expired, false otherwise
Implements bst::ITimer.
References bst::clck::now(), start_, and timeout_ms_.
Referenced by main(), and TEST().
setTimeout()
void bst::Timer::setTimeout (int timeout_ms) override virtual
Set the timeout of the timer.
Parameters
timeout_ms The timeout in milliseconds
Implements bst::ITimer.
References timeout_ms_.
Referenced by TEST().
setDone()
void bst::Timer::setDone () override virtual
Set the timer to be done. Changes the start time.
Implements bst::ITimer.
References bst::clck::now(), start_, and timeout_ms_.
Member Data Documentation
start_
bst::clck::TimePoint bst::Timer::start_ = bst::clck::Clock::now() private
Referenced by isDone(), reset(), and setDone().
timeout_ms_
int bst::Timer::timeout_ms_ private
Referenced by isDone(), setDone(), and setTimeout().