BoosterSeat: bst::Pressure Class Reference
bst::Pressure Class Reference
#include <science.hpp>
Public Member Functions
Pressure ()=default
double atmospheres () const
double inchesMercury () const
double millibars () const
double pascals () const
double psi () const
void setFromAtmospheres (double atmospheres)
void setFromInchesMercury (double inches_mercury)
void setFromMillibars (double millibars)
void setFromPascals (double pascals)
void setFromPSI (double psi)
Private Attributes
double pressure_pascals_ = 0.0
Constructor & Destructor Documentation
Pressure()
bst::Pressure::Pressure () default
Member Function Documentation
setFromPascals()
void bst::Pressure::setFromPascals (double pascals)
References pascals(), and pressure_pascals_.
Referenced by TEST().
pascals()
double bst::Pressure::pascals () const
References pressure_pascals_.
Referenced by setFromPascals(), and TEST().
setFromMillibars()
void bst::Pressure::setFromMillibars (double millibars)
References millibars(), and pressure_pascals_.
Referenced by TEST().
millibars()
double bst::Pressure::millibars () const
References pressure_pascals_.
Referenced by setFromMillibars(), and TEST().
setFromInchesMercury()
void bst::Pressure::setFromInchesMercury (double inches_mercury)
References pressure_pascals_.
Referenced by TEST().
inchesMercury()
double bst::Pressure::inchesMercury () const
References pressure_pascals_.
Referenced by TEST().
setFromPSI()
void bst::Pressure::setFromPSI (double psi)
References pressure_pascals_, and psi().
Referenced by TEST().
psi()
double bst::Pressure::psi () const
References pressure_pascals_.
Referenced by setFromPSI(), and TEST().
setFromAtmospheres()
void bst::Pressure::setFromAtmospheres (double atmospheres)
References atmospheres(), and pressure_pascals_.
atmospheres()
double bst::Pressure::atmospheres () const
References pressure_pascals_.
Referenced by setFromAtmospheres(), and TEST().
Member Data Documentation
pressure_pascals_
double bst::Pressure::pressure_pascals_ = 0.0 private
Referenced by atmospheres(), inchesMercury(), millibars(), pascals(), psi(), setFromAtmospheres(), setFromInchesMercury(), setFromMillibars(), setFromPascals(), and setFromPSI().