BoosterSeat: bst::geo Namespace Reference
bst::geo Namespace Reference
Classes
class Path
A path of geographical points.
class Point
A geographical point.
Functions
double distance (const Point &point_a, const Point &point_b)
Get the distance between two points in kilometers.
Function Documentation
distance()
double bst::geo::distance (const Point & point_a, const Point & point_b)
Get the distance between two points in kilometers.
Parameters
point_a The first point.
point_b The second point.
Returns
double The distance between the two points in kilometers.
References bst::math::D2R, bst::geo::Point::latitude(), and bst::geo::Point::longitude().
Referenced by bst::geo::Path::distance(), and TEST().