BoosterSeat: BoosterSeat::layout Namespace Reference
BoosterSeat::layout Namespace Reference
Enumerations
enum class Alignment { LEFT , RIGHT , CENTER }
Functions
std::string fixedWidthRow (const std::vector< std::string > &row, const Alignment align, const int row_width)
std::string fixedWidthString (const std::string &s, const Alignment align, const int width)
std::string simpleColumns (const std::vector< std::vector< std::string >> &rows, const Alignment align, const int column_width)
Enumeration Type Documentation
Alignment
enum BoosterSeat::layout::Alignment strong
Enumerator
LEFT
RIGHT
CENTER
Function Documentation
simpleColumns()
std::string BoosterSeat::layout::simpleColumns (const std::vector< std::vector< std::string >> & rows, const Alignment align, const int column_width)
References align_cases().
Referenced by main().
fixedWidthRow()
std::string BoosterSeat::layout::fixedWidthRow (const std::vector< std::string > & row, const Alignment align, const int row_width)
References align_cases().
Referenced by main().
fixedWidthString()
std::string BoosterSeat::layout::fixedWidthString (const std::string & s, const Alignment align, const int width)
References align_cases().
Referenced by main().