BoosterSeat: bst Namespace Reference
bst Namespace Reference
Namespaces
clck
filesystem
fs_int
Internal inline functions used only in this file.
geo
layout
math
string
template_tools
time
Classes
class BoosterSeatException
class Process
A class to handle linux process calls.
struct raii_char_str
class RollingAverage
Moving average calculator.
class Stopwatch
class Time
The generic time class for BoosterSeat. Uses UTC time.
class Timer
A simple timer class for timing events.
Enumerations
enum class ErrorNumber {
UNSPECIFIED = 0 , FS_PATH_DOES_NOT_EXIST = 1 , FS_PATH_ALREADY_EXISTS = 2 , FS_PATH_NOT_REGULAR_FILE = 3 ,
FS_PATH_NOT_DIRECTORY = 4 , FS_FILE_NOT_VALID = 5 , FS_NO_WRITE_PERMISSIONS = 6 , FS_NO_READ_PERMISSIONS = 7 ,
FS_INVALID_SIZE_UNIT = 8 , TIME_INVALID_TIMEZONE = 9 , GEO_INVALID_LATITUDE = 10 , GEO_INVALID_LONGITUDE = 11 ,
TIME_INVALID_TIME = 12 , PROCESS_NOT_COMPLETE = 13 , PROCESS_TIMEOUT = 14 , NOT_YET_IMPLEMENTED
}
enum class Resolution { SECONDS , MILLISECONDS , MICROSECONDS }
Functions
bool containsPrefix (const std::string &str, const std::string &prefix)
Checks if a string contains a prefix.
bool containsSubstring (const std::string &str, const std::string &sub)
Checks if a string contains a substring.
bool containsSuffix (const std::string &str, const std::string &suffix)
Checks if a string contains a suffix.
double doubleToPrecisionTwo (double)
Rounds a double to two decimal places. For example: 1.2345 -> 1.23.
bool isApproxEqual (double a, double b, double epsilon)
Just a simple function to compare two doubles by a given epsilon.
bool isApproxEqualPercent (const double a, const double b, const double percent)
std::string randomHexString (unsigned int length)
Generates a random hex string of the given length.
std::string rndTs (double d, int precision)
void sleep (int32_t milliseconds)
Variables
constexpr int K_PIPE_READ = 0
constexpr int K_PIPE_WRITE = 1
constexpr int kPrecision = 6
Enumeration Type Documentation
ErrorNumber
enum bst::ErrorNumber strong
Enumerator
UNSPECIFIED
Default value, just for backwards compatibility. Should not be used in new code.
FS_PATH_DOES_NOT_EXIST
Path does not exist when it should. Includes path in message.
FS_PATH_ALREADY_EXISTS
Path already exists when it should not. Includes path in message.
FS_PATH_NOT_REGULAR_FILE
Path is not a regular file. Includes path in message.
FS_PATH_NOT_DIRECTORY
Path is not a directory. Includes path in message.
FS_FILE_NOT_VALID
File is not valid. Includes if/ofstream error code in message.
Format: "Stream errno:<errorno> | <path>"
FS_NO_WRITE_PERMISSIONS
Throw if write permissions are required but do not exist.
FS_NO_READ_PERMISSIONS
Throw if read permissions are required but do not exist.
FS_INVALID_SIZE_UNIT
Thrown if an invalid size unit is used.
TIME_INVALID_TIMEZONE
Thrown if an invalid time zone is used.
GEO_INVALID_LATITUDE
Latitude is out of range/invalid.
GEO_INVALID_LONGITUDE
Longitude is out of range/invalid.
TIME_INVALID_TIME
Invalid time.
PROCESS_NOT_COMPLETE
Part of bst::Process, thrown if the process is not yet complete yet a method is called that requires the process to be complete. Call waitToComplete first.
PROCESS_TIMEOUT
Part of bst::Process, thrown if the process times out.
NOT_YET_IMPLEMENTED
Throws if a feature is not yet implemented.
Resolution
enum bst::Resolution strong
Enumerator
SECONDS
MILLISECONDS
MICROSECONDS
Function Documentation
doubleToPrecisionTwo()
double bst::doubleToPrecisionTwo (double d)
Rounds a double to two decimal places. For example: 1.2345 -> 1.23.
Parameters
double The double to round.
Returns
double The rounded double.
isApproxEqual()
bool bst::isApproxEqual (double a, double b, double epsilon) inline
Just a simple function to compare two doubles by a given epsilon.
Todo:
needs to be tested.
Parameters
a - The first double.
b - The second double.
epsilon - The maximum difference between the two doubles.
Returns
true - The two doubles are equal.
false - The two doubles are not equal.
Referenced by isApproxEqualPercent().
isApproxEqualPercent()
bool bst::isApproxEqualPercent (const double a, const double b, const double percent) inline
Todo:
needs to be tested.
Parameters
a
b
percent - value between 0.0 and 1.0
Returns
true
false
References isApproxEqual().
Referenced by validateSize().
rndTs()
std::string bst::rndTs (double d, int precision) inline
randomHexString()
std::string bst::randomHexString (unsigned int length)
Generates a random hex string of the given length.
Parameters
length - The length of the string to generate.
Returns
std::string - The generated string.
Referenced by main().
sleep()
void bst::sleep (int32_t milliseconds) inline
Referenced by main(), TEST(), and bst::Process::waitToComplete().
containsSubstring()
bool bst::containsSubstring (const std::string & str, const std::string & sub) inline
Checks if a string contains a substring.
Parameters
str - The string to check
sub - The substring to check for
Returns
true - If the string contains the substring
false - If the string does not contain the substring
containsPrefix()
bool bst::containsPrefix (const std::string & str, const std::string & prefix) inline
Checks if a string contains a prefix.
Parameters
str - The string to check
prefix - The prefix to check for
Returns
true - If the string contains the prefix
false - If the string does not contain the prefix
containsSuffix()
bool bst::containsSuffix (const std::string & str, const std::string & suffix) inline
Checks if a string contains a suffix.
Parameters
str - The string to check
suffix - The suffix to check for
Returns
true - If the string contains the suffix
false - If the string does not contain the suffix
Variable Documentation
kPrecision
constexpr int bst::kPrecision = 6 inline constexpr
K_PIPE_READ
constexpr int bst::K_PIPE_READ = 0 inline constexpr
Referenced by bst::Process::child(), and bst::Process::run().
K_PIPE_WRITE
constexpr int bst::K_PIPE_WRITE = 1 inline constexpr
Referenced by bst::Process::child(), and bst::Process::run().