Boost_erSeat: internal Namespace Reference
internal Namespace Reference
Internal inline functions used only in this file.
Functions
double convertMbToUnit (const double size_mb, const fs::units::Size unit)
bool exists (const Path &path)
std::uintmax_t get_file_size_bytes (const Path &path)
bool has_read_permissions (const Path &path)
Returns true if the program has read permissions.
bool has_write_permission (const Path &path)
Returns true if the path if the program has write permissions.
bool is_directory (const Path &path)
Returns true if the path is a directory.
bool is_file (const Path &path)
Checks if a path is a regular file.
Detailed Description
Internal inline functions used only in this file.
Function Documentation
exists()
bool internal::exists (const Path & path) inline
Referenced by assertions::DoesNotExist(), and assertions::Exists().
is_file()
bool internal::is_file (const Path & path) inline
Checks if a path is a regular file.
Parameters
path - The path to check.
Returns
true - The path is a regular file.
false - The path is not a regular file.
is_directory()
bool internal::is_directory (const Path & path) inline
Returns true if the path is a directory.
Parameters
path - The path to check.
Returns
true - The path is a directory.
false - The path is not a directory.
Referenced by assertions::IsDirectory().
has_write_permission()
bool internal::has_write_permission (const Path & path) inline
Returns true if the path if the program has write permissions.
Parameters
path - The path to check.
Returns
true - The program has write permissions.
false - The program does not have write permissions.
Referenced by assertions::WritePermissions().
has_read_permissions()
bool internal::has_read_permissions (const Path & path) inline
Returns true if the program has read permissions.
Parameters
path - The path to check.
Returns
true - The program has read permissions.
false - The program does not have read permissions.
Referenced by assertions::ReadPermissions().
get_file_size_bytes()
std::uintmax_t internal::get_file_size_bytes (const Path & path) inline
convertMbToUnit()
double internal::convertMbToUnit (const double size_mb, const fs::units::Size unit) inline