BoosterSeat: bst::clck Namespace Reference
bst::clck Namespace Reference
Namespaces
units
Typedefs
typedef std::chrono::high_resolution_clock Clock
typedef Clock::duration Duration
typedef std::chrono::time_point< Clock > TimePoint
Functions
TimePoint fromTimeT (time_t time)
int millisecondsElapsed (const TimePoint &time_point)
TimePoint now ()
int secondsElapsed (const TimePoint &time_point)
time_t toTimeT (const TimePoint &time_point)
Typedef Documentation
Clock
typedef std::chrono::high_resolution_clock bst::clck::Clock
TimePoint
typedef std::chrono::time_point<Clock> bst::clck::TimePoint
Duration
typedef Clock::duration bst::clck::Duration
Function Documentation
now()
TimePoint bst::clck::now () inline
Referenced by bst::getUnixTime(), bst::Timer::isDone(), main(), millisecondsElapsed(), bst::Timer::reset(), secondsElapsed(), bst::Timer::setDone(), and TEST().
secondsElapsed()
int bst::clck::secondsElapsed (const TimePoint & time_point) inline
References now().
Referenced by bst::time::elapsedAsciiClock().
millisecondsElapsed()
int bst::clck::millisecondsElapsed (const TimePoint & time_point) inline
References now().
toTimeT()
time_t bst::clck::toTimeT (const TimePoint & time_point) inline
Referenced by bst::time::dateAndTimeString(), and bst::time::timeString().
fromTimeT()
TimePoint bst::clck::fromTimeT (time_t time) inline
Referenced by bst::time::dateAndTimeToTimePoint().