BoosterSeat: BoosterSeat::time Namespace Reference
BoosterSeat::time Namespace Reference
Enumerations
enum class TimeZone { UTC , LOCAL }
Functions
std::string dateAndTimeString (TimeZone time_zone=TimeZone::LOCAL, char date_delimiter='-', char between_delimiter=' ', char time_delimiter=':', BoosterSeat::clck::TimePoint time_point=BoosterSeat::clck::now())
Get the date and time in the format: YYYY-MM-DD HH:MM:SS.
BoosterSeat::clck::TimePoint dateAndTimeToTimePoint (int year, int month, int day, int hour, int minute, int second)
Convert a date and time to a BoosterSeat::clck::TimePoint.
std::string dateString (TimeZone time_zone=TimeZone::LOCAL, char delimiter='-')
std::string elapsedAsciiClock (const BoosterSeat::clck::TimePoint &time_point)
std::string timeString (TimeZone time_zone=TimeZone::LOCAL, char delimiter=':', BoosterSeat::clck::TimePoint time_point=BoosterSeat::clck::now())
Get the time in format: HH:MM:SS (24 hour clock) for a given time zone.
Enumeration Type Documentation
TimeZone
enum BoosterSeat::time::TimeZone strong
Enumerator
UTC
LOCAL
Function Documentation
elapsedAsciiClock()
std::string BoosterSeat::time::elapsedAsciiClock (const BoosterSeat::clck::TimePoint & time_point)
References BoosterSeat::clck::secondsElapsed().
Referenced by main().
timeString()
std::string BoosterSeat::time::timeString (TimeZone time_zone = TimeZone::LOCAL, char delimiter = ':', BoosterSeat::clck::TimePoint time_point = BoosterSeat::clck::now())
Get the time in format: HH:MM:SS (24 hour clock) for a given time zone.
Parameters
time_zone - The time zone to get the time in
delimiter - The delimiter to use (default: ':')
time - The time to get the string for (default: current time)
Returns
std::string - The time string
References getTm(), timeFormatString(), and BoosterSeat::clck::toTimeT().
Referenced by main().
dateString()
std::string BoosterSeat::time::dateString (TimeZone time_zone = TimeZone::LOCAL, char delimiter = '-')
References dateFormatString(), and getTm().
Referenced by main().
dateAndTimeString()
std::string BoosterSeat::time::dateAndTimeString (TimeZone time_zone = TimeZone::LOCAL, char date_delimiter = '-', char between_delimiter = ' ', char time_delimiter = ':', BoosterSeat::clck::TimePoint time_point = BoosterSeat::clck::now())
Get the date and time in the format: YYYY-MM-DD HH:MM:SS.
Returns
std::string
References dateFormatString(), getTm(), timeFormatString(), and BoosterSeat::clck::toTimeT().
Referenced by main().
dateAndTimeToTimePoint()
BoosterSeat::clck::TimePoint BoosterSeat::time::dateAndTimeToTimePoint (int year, int month, int day, int hour, int minute, int second)
Convert a date and time to a BoosterSeat::clck::TimePoint.
All parameters are clamped to their respective ranges.
Parameters
year - The year (e.g. 2023, must be greater than 1970)
month - The month (1 - 12)
day - The day (1 - 31)
hour - The hour (0 - 23)
minute - The minute (0 - 59)
second - The second (0 - 59)
Returns
BoosterSeat::clck::TimePoint - The time point
References BoosterSeat::clck::fromTimeT(), and BoosterSeat::TIME_INVALID_TIME.
Referenced by main().