BoosterSeat: BoosterSeat::clck Namespace Reference
BoosterSeat::clck Namespace Reference
Namespaces
units
Typedefs
typedef std::chrono::high_resolution_clock Clock
typedef Clock::duration Duration
typedef std::chrono::time_point< Clock > TimePoint
Functions
TimePoint fromTimeT (time_t time)
int millisecondsElapsed (const TimePoint &time_point)
TimePoint now ()
int secondsElapsed (const TimePoint &time_point)
time_t toTimeT (const TimePoint &time_point)
Typedef Documentation
Clock
typedef std::chrono::high_resolution_clock BoosterSeat::clck::Clock
TimePoint
typedef std::chrono::time_point<Clock> BoosterSeat::clck::TimePoint
Duration
typedef Clock::duration BoosterSeat::clck::Duration
Function Documentation
now()
TimePoint BoosterSeat::clck::now () inline
Referenced by BoosterSeat::Timer::isDone(), main(), millisecondsElapsed(), BoosterSeat::Timer::reset(), and secondsElapsed().
secondsElapsed()
int BoosterSeat::clck::secondsElapsed (const TimePoint & time_point) inline
References now().
Referenced by BoosterSeat::time::elapsedAsciiClock().
millisecondsElapsed()
int BoosterSeat::clck::millisecondsElapsed (const TimePoint & time_point) inline
References now().
toTimeT()
time_t BoosterSeat::clck::toTimeT (const TimePoint & time_point) inline
Referenced by BoosterSeat::time::dateAndTimeString(), and BoosterSeat::time::timeString().
fromTimeT()
TimePoint BoosterSeat::clck::fromTimeT (time_t time) inline
Referenced by BoosterSeat::time::dateAndTimeToTimePoint().