BoosterSeat: assertions Namespace Reference
assertions Namespace Reference
Functions
void DoesNotExist (const Path &path)
Checks if a path exists, otherwise it will throw an exception.
void Exists (const Path &path)
Checks if a path exists, otherwise it will throw an exception.
template<typename T >
void FileValid (const Path &path, T &file)
Checks if the file is open and valid, otherwise it will throw an exception with the error code. This function is only for ifstream and ofstream. Used after opening a file.
void IsDirectory (const Path &path)
Checks if the path exists and is a directory, otherwise it will throw an exception.
void IsRegularFile (const Path &path)
Checks if the path exists and is a regular file, otherwise it will throw an exception.
void ReadPermissions (const Path &path)
Only works on Linux at the moment, requires the <unistd.h> header.
void WritePermissions (const Path &path)
Checks a program has write permissions to the file or directory at the path, if not, throws an exception. Only works on Linux at the moment, requires the <unistd.h> header.
Function Documentation
Exists()
void assertions::Exists (const Path & path) inline
Checks if a path exists, otherwise it will throw an exception.
Parameters
path - The path to check.
Exceptions
BoosterSeatException - If the path does not exist.
References internal::exists().
Referenced by IsDirectory(), and IsRegularFile().
DoesNotExist()
void assertions::DoesNotExist (const Path & path) inline
Checks if a path exists, otherwise it will throw an exception.
Parameters
path - The path to check.
Exceptions
BoosterSeatException - If the path does exist.
References internal::exists().
IsRegularFile()
void assertions::IsRegularFile (const Path & path) inline
Checks if the path exists and is a regular file, otherwise it will throw an exception.
Parameters
path - The path to check.
Exceptions
BoosterSeatException - If the path does not exist or is not a
References Exists().
IsDirectory()
void assertions::IsDirectory (const Path & path) inline
Checks if the path exists and is a directory, otherwise it will throw an exception.
Parameters
path - The path to check.
Exceptions
BoosterSeatException - If the path does not exist or is not a
References Exists(), and internal::is_directory().
FileValid()
template<typename T > void assertions::FileValid (const Path & path, T & file) inline
Checks if the file is open and valid, otherwise it will throw an exception with the error code. This function is only for ifstream and ofstream. Used after opening a file.
Parameters
path - The path to the file.
file - The fstream object to check.
WritePermissions()
void assertions::WritePermissions (const Path & path) inline
Checks a program has write permissions to the file or directory at the path, if not, throws an exception. Only works on Linux at the moment, requires the <unistd.h> header.
Parameters
path - The path to the file.
Exceptions
BoosterSeatException - If the file does not have write permissions.
References internal::has_write_permission().
ReadPermissions()
void assertions::ReadPermissions (const Path & path) inline
Only works on Linux at the moment, requires the <unistd.h> header.
Parameters
path
Exceptions
BoosterSeatException - If the file does not have read permissions.
References internal::has_read_permissions().