BoosterSeat: process_test.cpp File Reference
process_test.cpp File Reference
#include <BoosterSeat/process.hpp>
#include <iostream>
#include <sstream>
#include "gtest/gtest.h"
Functions
std::string getOutput (bst::Process &p)
TEST (bst_process, basic_error)
TEST (bst_process, basic_exit_code)
TEST (bst_process, basic_input)
TEST (bst_process, basic_output)
TEST (bst_process, command_timeout)
Function Documentation
getOutput()
std::string getOutput (bst::Process & p) inline
References bst::Process::getExitCode(), bst::Process::getStderr(), and bst::Process::getStdout().
Referenced by TEST().
TEST() [1/5]
TEST (bst_process , basic_output)
References getOutput(), and bst::Process::waitToComplete().
TEST() [2/5]
TEST (bst_process , basic_exit_code)
References getOutput(), and bst::Process::waitToComplete().
TEST() [3/5]
TEST (bst_process , basic_error)
References getOutput(), and bst::Process::waitToComplete().
TEST() [4/5]
TEST (bst_process , basic_input)
References getOutput(), and bst::Process::writeToInStream().
TEST() [5/5]
TEST (bst_process , command_timeout)
References bst::BoosterSeatException::errorNumberEnum(), bst::PROCESS_TIMEOUT, and bst::Process::waitToComplete().