BoosterSeat: stopwatch_test.cpp File Reference
stopwatch_test.cpp File Reference
#include <iostream>
#include <BoosterSeat/sleep.hpp>
#include <BoosterSeat/stopwatch.hpp>
#include "gtest/gtest.h"
Functions
TEST (StopwatchTest, DefaultConstructor)
TEST (StopwatchTest, IStopwatch)
TEST (StopwatchTest, KeepsRunningTotal)
TEST (StopwatchTest, ResetKeepsRunning)
TEST (StopwatchTest, ResetStopsByDefault)
TEST (StopwatchTest, SoftwareStopwatch)
TEST (StopwatchTest, StartAndStop)
TEST (StopwatchTest, Units)
Function Documentation
TEST() [1/8]
TEST (StopwatchTest , DefaultConstructor)
References bst::Stopwatch::elapsedMicroseconds(), and bst::Stopwatch::isRunning().
TEST() [2/8]
TEST (StopwatchTest , StartAndStop)
References bst::Stopwatch::isRunning(), bst::Stopwatch::start(), and bst::Stopwatch::stop().
TEST() [3/8]
TEST (StopwatchTest , Units)
References bst::Stopwatch::elapsedMicrosecondsF(), bst::Stopwatch::elapsedMillisecondsF(), bst::Stopwatch::elapsedSecondsF(), bst::sleep(), bst::Stopwatch::start(), and bst::Stopwatch::stop().
TEST() [4/8]
TEST (StopwatchTest , KeepsRunningTotal)
References bst::Stopwatch::elapsedSecondsF(), bst::sleep(), bst::Stopwatch::start(), and bst::Stopwatch::stop().
TEST() [5/8]
TEST (StopwatchTest , ResetStopsByDefault)
References bst::Stopwatch::elapsedMicroseconds(), bst::Stopwatch::isRunning(), bst::Stopwatch::reset(), bst::sleep(), and bst::Stopwatch::start().
TEST() [6/8]
TEST (StopwatchTest , ResetKeepsRunning)
References bst::Stopwatch::elapsedMicroseconds(), bst::Stopwatch::isRunning(), bst::Stopwatch::reset(), bst::sleep(), and bst::Stopwatch::start().
TEST() [7/8]
TEST (StopwatchTest , IStopwatch)
References bst::IStopwatch::elapsedMilliseconds(), bst::sleep(), bst::IStopwatch::start(), and bst::IStopwatch::stop().
TEST() [8/8]
TEST (StopwatchTest , SoftwareStopwatch)
References bst::IStopwatch::elapsedMilliseconds(), bst::IStopwatch::start(), bst::IStopwatch::stop(), and bst::SoftwareStopwatch::tick().