BoosterSeat: timer_test.cpp File Reference
timer_test.cpp File Reference
#include "gtest/gtest.h"
#include <BoosterSeat/sleep.hpp>
#include <BoosterSeat/timer.hpp>
Functions
TEST (bst_timer, SoftwareTimer_basic_test)
TEST (bst_timer, Timer_basic_test)
Detailed Description
Date
2024-10-17
Author
Joshua Jerred (https://joshuajer.red)
Copyright
Copyright (c) 2023
Function Documentation
TEST() [1/2]
TEST (bst_timer , Timer_basic_test)
References bst::Timer::isDone(), bst::Timer::reset(), bst::Timer::setTimeout(), and bst::sleep().
TEST() [2/2]
TEST (bst_timer , SoftwareTimer_basic_test)
References bst::SoftwareTimer::isDone(), bst::SoftwareTimer::reset(), bst::SoftwareTimer::setDone(), and bst::SoftwareTimer::setNotDone().