BoosterSeat: time_string_test.cpp File Reference
time_string_test.cpp File Reference
#include <BoosterSeat/time.hpp>
#include "gtest/gtest.h"
#include <iostream>
Functions
TEST (bstTimeClass, basic_string)
TEST (bstTimeClass, getters)
TEST (bstTimeClass, greaterThanLessThanOperators)
TEST (bstTimeClass, setToNow)
Function Documentation
TEST() [1/4]
TEST (bstTimeClass , basic_string)
References bst::Time::fromString(), and bst::Time::toString().
TEST() [2/4]
TEST (bstTimeClass , getters)
References bst::Time::fromString(), bst::Time::getDay(), bst::Time::getHour(), bst::Time::getMinute(), bst::Time::getMonth(), bst::Time::getSecond(), and bst::Time::getYear().
TEST() [3/4]
TEST (bstTimeClass , setToNow)
References bst::Time::getDay(), bst::Time::getHour(), bst::Time::getMinute(), bst::Time::getMonth(), bst::Time::getSecond(), bst::Time::getYear(), BoosterSeat::clck::now(), and bst::Time::setToNow().
TEST() [4/4]
TEST (bstTimeClass , greaterThanLessThanOperators)
References bst::Time::fromString().