Boost_erSeat: time.cpp File Reference
time.cpp File Reference
#include <BoosterSeat/exception.hpp>
#include <BoosterSeat/time.hpp>
#include <algorithm>
Functions
std::string dateFormatString (const char delimiter)
std::tm getTm (const BoosterSeat::time::TimeZone time_zone, time_t time)
std::string timeFormatString (const char delimiter)
Function Documentation
getTm()
std::tm getTm (const BoosterSeat::time::TimeZone time_zone, time_t time) inline
References BoosterSeat::time::LOCAL, BoosterSeat::TIME_INVALID_TIMEZONE, and BoosterSeat::time::UTC.
Referenced by BoosterSeat::time::dateAndTimeString(), BoosterSeat::time::dateString(), and BoosterSeat::time::timeString().
timeFormatString()
std::string timeFormatString (const char delimiter) inline
Referenced by BoosterSeat::time::dateAndTimeString(), and BoosterSeat::time::timeString().
dateFormatString()
std::string dateFormatString (const char delimiter) inline
Referenced by BoosterSeat::time::dateAndTimeString(), and BoosterSeat::time::dateString().