BoosterSeat: time_class_test.cpp File Reference
time_class_test.cpp File Reference
#include <BoosterSeat/sleep.hpp>
#include <BoosterSeat/time.hpp>
#include "gtest/gtest.h"
#include <iostream>
Functions
TEST (bstTimeClass, basic_string)
TEST (bstTimeClass, constructors)
TEST (bstTimeClass, getters)
TEST (bstTimeClass, greaterThanLessThanOperators)
TEST (bstTimeClass, secondsFromNow)
TEST (bstTimeClass, setToNow)
Function Documentation
TEST() [1/6]
TEST (bstTimeClass , constructors)
References bst::Time::secondsFromNow(), and bst::Time::toString().
TEST() [2/6]
TEST (bstTimeClass , basic_string)
References bst::Time::fromString(), and bst::Time::toString().
TEST() [3/6]
TEST (bstTimeClass , getters)
References bst::Time::fromString(), bst::Time::getDay(), bst::Time::getHour(), bst::Time::getMinute(), bst::Time::getMonth(), bst::Time::getSecond(), and bst::Time::getYear().
TEST() [4/6]
TEST (bstTimeClass , setToNow)
References bst::Time::getDay(), bst::Time::getHour(), bst::Time::getMinute(), bst::Time::getMonth(), bst::Time::getSecond(), bst::Time::getYear(), bst::clck::now(), and bst::Time::setToNow().
TEST() [5/6]
TEST (bstTimeClass , greaterThanLessThanOperators)
References bst::Time::fromString().
TEST() [6/6]
TEST (bstTimeClass , secondsFromNow)
References bst::Time::fromString(), bst::Time::secondsFromNow(), bst::Time::setToNow(), and bst::sleep().