BoosterSeat: visual_tests.cpp File Reference
visual_tests.cpp File Reference
#include <BoosterSeat/random.hpp>
#include <BoosterSeat/sleep.hpp>
#include <BoosterSeat/string_formatting.hpp>
#include <BoosterSeat/time.hpp>
#include <BoosterSeat/timer.hpp>
#include <iostream>
Functions
int main ()
Function Documentation
main()
int main ()
References BoosterSeat::layout::CENTER, BoosterSeat::time::dateAndTimeString(), BoosterSeat::time::dateAndTimeToTimePoint(), BoosterSeat::time::dateString(), BoosterSeat::time::elapsedAsciiClock(), BoosterSeat::layout::fixedWidthRow(), BoosterSeat::layout::fixedWidthString(), BoosterSeat::layout::LEFT, BoosterSeat::clck::now(), BoosterSeat::randomHexString(), BoosterSeat::layout::RIGHT, BoosterSeat::layout::simpleColumns(), BoosterSeat::threadSleep(), and BoosterSeat::time::timeString().