name: BoosterSeat CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit_tests:
    name: Build Library & Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..
    - name: Build BoosterSeat
      run: |
        cd build
        make BoosterSeat
    - name: Build Tests
      run: |
        cd build
        make unit_tests
    - name: Run Tests
      run: |
        cd build/tests
        ./unit_tests
